Tensors are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

In [1]:
import torch

In [2]:
x=torch.empty(6,9)
print(x)

tensor([[-2.4972e-11,  7.0205e-43, -2.3531e-12,  7.0205e-43,  0.0000e+00,
          0.0000e+00,  2.1019e-44,  0.0000e+00, -1.5229e-11],
        [ 7.0205e-43,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          2.1019e-44,  0.0000e+00, -1.2703e-11,  7.0205e-43],
        [ 1.7796e-43,  0.0000e+00,  0.0000e+00,  0.0000e+00,  2.1019e-44,
          0.0000e+00, -2.4279e-11,  7.0205e-43,  1.7796e-43],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  2.1019e-44,  0.0000e+00,
         -1.1159e-12,  7.0205e-43,  1.7796e-43,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  2.1019e-44,  0.0000e+00, -2.2811e-11,
          7.0205e-43,  1.7796e-43,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  2.1019e-44,  0.0000e+00, -2.4791e-11,  7.0205e-43,
          1.7796e-43,  0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [5]:
y=torch.rand(5,3)
print(y)

tensor([[0.1480, 0.9864, 0.2354],
        [0.3847, 0.3259, 0.5614],
        [0.2336, 0.4544, 0.3184],
        [0.8569, 0.2899, 0.0944],
        [0.9296, 0.7840, 0.6513]])


In [7]:
y=torch.zeros(5,3,dtype=torch.long)
print(y)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


#### Construct a tensor directly from data:


In [8]:
y = torch.tensor([5.5, 3])
print(y)

tensor([5.5000, 3.0000])


 ###### create a tensor based on an existing tensor. 
 These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by use

In [13]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

y = torch.randn_like(y, dtype=torch.float)    # override dtype!
print(y)
print(y.size()) #torch.Size is in fact a tuple, so it supports all tuple operations.

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([2.0551, 0.6875])
torch.Size([2])


###### Operations

In [15]:
a=torch.rand(3,4)
print(a)
b=torch.rand(3,4)
print(b)

tensor([[0.0719, 0.5628, 0.3523, 0.3193],
        [0.5753, 0.1280, 0.3894, 0.1557],
        [0.1336, 0.6422, 0.5267, 0.4748]])
tensor([[0.5894, 0.0928, 0.0994, 0.2394],
        [0.0759, 0.9523, 0.6718, 0.6349],
        [0.9774, 0.4634, 0.1530, 0.2365]])


In [21]:
print(a+b)
##
res=torch.empty_like(a)
torch.add(a,b,out=res)
print(res)
###
a.add_(b)
print(a)
# Any operation that mutates a tensor in-place is post-fixed with an _. 
# For example: x.copy_(y), x.t_(), will change x

tensor([[1.8400, 0.8413, 0.6503, 1.0374],
        [0.8029, 2.9849, 2.4048, 2.0603],
        [3.0658, 2.0324, 0.9858, 1.1841]])
tensor([[1.8400, 0.8413, 0.6503, 1.0374],
        [0.8029, 2.9849, 2.4048, 2.0603],
        [3.0658, 2.0324, 0.9858, 1.1841]])
tensor([[1.8400, 0.8413, 0.6503, 1.0374],
        [0.8029, 2.9849, 2.4048, 2.0603],
        [3.0658, 2.0324, 0.9858, 1.1841]])


You can use standard NumPy-like indexing with all bells and whistles!

In [25]:
print(x[:,1])

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


###### reshape or resize the tensor

In [27]:
c=a.view(12)
print(c)
d=a.view(-1,2)
print(d)

tensor([1.8400, 0.8413, 0.6503, 1.0374, 0.8029, 2.9849, 2.4048, 2.0603, 3.0658,
        2.0324, 0.9858, 1.1841])
tensor([[1.8400, 0.8413],
        [0.6503, 1.0374],
        [0.8029, 2.9849],
        [2.4048, 2.0603],
        [3.0658, 2.0324],
        [0.9858, 1.1841]])


In [30]:
# if you have a one element tensor, 
# use .item() to get the value as a Python number
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.7535])
0.753531277179718


[more opeartions](https://pytorch.org/docs/torch)

##### NumPy Bridge

In [33]:
e = a.numpy()
print(e)

[[1.840004   0.84129965 0.6503469  1.0373697 ]
 [0.8029381  2.984898   2.404752   2.0603335 ]
 [3.0657861  2.0324054  0.9857589  1.1841494 ]]


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

In [37]:
import numpy as np
g = np.ones(5)
f = torch.from_numpy(g)
np.add(g, 1, out=g)
print(g)
print(f)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


##### CUDA tensors

#### Tensors can be moved onto any device using the .to method.

In [2]:
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!